---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 10.19.19.45
  connection: local
  
tasks:
   - name: Create a pool
     bigip_pool:
         lb_method: ratio-member
         name: web
         password: admin
         server: 10.19.19.45
         slow_ramp_time: 120
         user: admin
         validate_certs: no
     delegate_to: localhost
     
