---
- name: copy device running configuration
  ios_command:
      commands:
         - show run
      provider: "{{ ios_provider }}"
  register: tech
  
- name: save out
  copy:
     content: "{{ tech.stdout[0] }}"
     dest: "/var/lib/awx/projects/backups/{{ ansible_date_time.date }}_{{ inventory_hostname }}.txt"
