---
- name: copy device running configuration
  ios_command:
      commands:
         - show tech-support
      provider: "{{ ios_provider }}"
  register: tech
- name: save out
  copy:
     content: "{{ tech.stdout[0] }}"
     dest: "https://github.com/andynosy/KLD_POC_PLAYBOOKS.git/backups/{{ ansible_date_time.date }}_{{ inventory_hostname }}.txt"
